server:
  port: 8086
  servlet:
    context-path: /profile

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: profile-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  application:
    name: profile-service


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecomerce_profile
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: "298d452efb93a5b2eb1005d0bec28a1cc90d4b51ab055e32499119fbe606a61e9f9a8f0f"