import { InventoryItem } from '@/types/inventory.types';

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    pid: 'v001a',
    name: 'Sony WH-1000XM5 — Black',
    sku: 'SONY-WH5-BLK',
    category: 'Electronics',
    price: 349,
    stock: 42,
    reservedQuantity: 5,
    threshold: 10,
    sold7: 8,
    status: 'IN_STOCK',
  },
  {
    pid: 'v001b',
    name: 'Sony WH-1000XM5 — Silver',
    sku: 'SONY-WH5-SLV',
    category: 'Electronics',
    price: 399,
    stock: 7,
    reservedQuantity: 2,
    threshold: 10,
    sold7: 3,
    status: 'LOW_STOCK',
  },
  {
    pid: 'v002b',
    name: 'Apple iPad Pro 12.9" — 256GB WiFi',
    sku: 'APPLE-IPAD-256W',
    category: 'Electronics',
    price: 1299,
    stock: 0,
    reservedQuantity: 0,
    threshold: 5,
    sold7: 0,
    status: 'OUT_OF_STOCK',
  },
  {
    pid: 'v003a',
    name: 'Samsung OLED TV — 55 inch',
    sku: 'SAM-TV-55',
    category: 'Electronics',
    price: 1299,
    stock: 15,
    reservedQuantity: 3,
    threshold: 5,
    sold7: 2,
    status: 'IN_STOCK',
  },
  {
    pid: 'v004c',
    name: 'Nike Air Max 270 React — Black/40',
    sku: 'NIKE-AM270-BLK-40',
    category: 'Fashion',
    price: 129,
    stock: 5,
    reservedQuantity: 1,
    threshold: 8,
    sold7: 6,
    status: 'LOW_STOCK',
  },
  {
    pid: 'v004d',
    name: 'Nike Air Max 270 React — Black/41',
    sku: 'NIKE-AM270-BLK-41',
    category: 'Fashion',
    price: 129,
    stock: 28,
    reservedQuantity: 4,
    threshold: 8,
    sold7: 9,
    status: 'IN_STOCK',
  },
  {
    pid: 'v006a',
    name: 'Garmin Forerunner 955 — Black',
    sku: 'GRMN-FR955-BLK',
    category: 'Sports',
    price: 449,
    stock: 0,
    reservedQuantity: 0,
    threshold: 5,
    sold7: 0,
    status: 'OUT_OF_STOCK',
  },
  {
    pid: 'v007b',
    name: 'Adjustable Dumbbell Set — Pair',
    sku: 'DBELL-ADJ-PAIR',
    category: 'Sports',
    price: 299,
    stock: 3,
    reservedQuantity: 1,
    threshold: 5,
    sold7: 4,
    status: 'LOW_STOCK',
  },
  {
    pid: 'v008a',
    name: 'Dyson V15 Detect — Yellow/Nickel',
    sku: 'DYSON-V15-YLW',
    category: 'Home',
    price: 699,
    stock: 19,
    reservedQuantity: 2,
    threshold: 5,
    sold7: 3,
    status: 'IN_STOCK',
  },
  {
    pid: 'v009b',
    name: 'Instant Pot Duo — 6 Quart',
    sku: 'IPOT-DUO-6QT',
    category: 'Home',
    price: 89,
    stock: 54,
    reservedQuantity: 7,
    threshold: 10,
    sold7: 12,
    status: 'IN_STOCK',
  },
  {
    pid: 'v010b',
    name: 'La Mer Moisturizing Cream — 30ml',
    sku: 'LAMER-CREME-30',
    category: 'Beauty',
    price: 159,
    stock: 8,
    reservedQuantity: 0,
    threshold: 10,
    sold7: 5,
    status: 'LOW_STOCK',
  },
  {
    pid: 'v011b',
    name: 'Dyson Airwrap — Prussian Blue',
    sku: 'DYSON-AWP-BLUE',
    category: 'Beauty',
    price: 549,
    stock: 0,
    reservedQuantity: 0,
    threshold: 5,
    sold7: 0,
    status: 'OUT_OF_STOCK',
  },
  {
    pid: 'v012a',
    name: 'Atomic Habits — Paperback',
    sku: 'BOOK-ATOMIC-PB',
    category: 'Books',
    price: 14,
    stock: 120,
    reservedQuantity: 10,
    threshold: 20,
    sold7: 25,
    status: 'IN_STOCK',
  },
  {
    pid: 'v014a',
    name: 'Logitech MX Master 3S — Graphite',
    sku: 'LOGI-MX3S-GRP',
    category: 'Electronics',
    price: 89,
    stock: 33,
    reservedQuantity: 6,
    threshold: 10,
    sold7: 7,
    status: 'IN_STOCK',
  },
];
