import { Order } from '@/types/order.types';

export const MOCK_ORDERS: Order[] = [
  // ─── PENDING ─────────────────────────────────────────────
  {
    id: 'ord-001',
    userId: 'mock-user-id',
    status: 'PENDING',
    totalAmount: 448,
    shippingAddress: {
      firstName: 'Nguyễn',
      lastName: 'Văn A',
      email: 'user@shopnow.com',
      phone: '0901234567',
      street: '123 Nguyễn Huệ',
      city: 'Hồ Chí Minh',
      state: 'HCM',
      zipCode: '700000',
      country: 'Vietnam',
    },
    orderItems: [
      {
        id: 'oi-001a',
        productVariantId: 'v001a',
        productName: 'Sony WH-1000XM5 Wireless Headphones',
        variantName: 'Black',
        quantity: 1,
        unitPrice: 349,
        subtotal: 349,
      },
      {
        id: 'oi-001b',
        productVariantId: 'v012a',
        productName: 'Atomic Habits',
        variantName: 'Paperback',
        quantity: 1,
        unitPrice: 14,
        subtotal: 14,
      },
    ],
    createdAt: '2024-03-18T10:30:00Z',
  },

  // ─── PENDING ─────────────────────────────────────────────
  {
    id: 'ord-002',
    userId: 'mock-user-id',
    status: 'PENDING',
    totalAmount: 1299,
    shippingAddress: {
      firstName: 'Nguyễn',
      lastName: 'Văn A',
      email: 'user@shopnow.com',
      phone: '0901234567',
      street: '123 Nguyễn Huệ',
      city: 'Hồ Chí Minh',
      state: 'HCM',
      zipCode: '700000',
      country: 'Vietnam',
    },
    orderItems: [
      {
        id: 'oi-002a',
        productVariantId: 'v002b',
        productName: 'Apple iPad Pro 12.9" M2',
        variantName: '256GB WiFi',
        quantity: 1,
        unitPrice: 1299,
        subtotal: 1299,
      },
    ],
    createdAt: '2024-03-17T14:15:00Z',
  },

  // ─── CONFIRMED ───────────────────────────────────────────
  {
    id: 'ord-003',
    userId: 'mock-user-id',
    status: 'CONFIRMED',
    totalAmount: 478,
    shippingAddress: {
      firstName: 'Nguyễn',
      lastName: 'Văn A',
      email: 'user@shopnow.com',
      phone: '0901234567',
      street: '123 Nguyễn Huệ',
      city: 'Hồ Chí Minh',
      state: 'HCM',
      zipCode: '700000',
      country: 'Vietnam',
    },
    orderItems: [
      {
        id: 'oi-003a',
        productVariantId: 'v006a',
        productName: 'Garmin Forerunner 955 GPS Watch',
        variantName: 'Black',
        quantity: 1,
        unitPrice: 449,
        subtotal: 449,
      },
      {
        id: 'oi-003b',
        productVariantId: 'v013b',
        productName: 'The Psychology of Money',
        variantName: 'Hardcover',
        quantity: 1,
        unitPrice: 20,
        subtotal: 20,
      },
    ],
    note: 'Giao hàng buổi sáng',
    createdAt: '2024-03-10T09:00:00Z',
  },

  // ─── SHIPPING ────────────────────────────────────────────
  {
    id: 'ord-004',
    userId: 'mock-user-id',
    status: 'SHIPPING',
    totalAmount: 299,
    shippingAddress: {
      firstName: 'Nguyễn',
      lastName: 'Văn A',
      email: 'user@shopnow.com',
      phone: '0901234567',
      street: '123 Nguyễn Huệ',
      city: 'Hồ Chí Minh',
      state: 'HCM',
      zipCode: '700000',
      country: 'Vietnam',
    },
    orderItems: [
      {
        id: 'oi-004a',
        productVariantId: 'v007b',
        productName: 'Adjustable Dumbbell Set',
        variantName: 'Pair',
        quantity: 1,
        unitPrice: 299,
        subtotal: 299,
      },
    ],
    createdAt: '2024-03-01T11:00:00Z',
  },

  // ─── DELIVERED ───────────────────────────────────────────
  {
    id: 'ord-005',
    userId: 'mock-user-id',
    status: 'DELIVERED',
    totalAmount: 267,
    shippingAddress: {
      firstName: 'Nguyễn',
      lastName: 'Văn A',
      email: 'user@shopnow.com',
      phone: '0901234567',
      street: '123 Nguyễn Huệ',
      city: 'Hồ Chí Minh',
      state: 'HCM',
      zipCode: '700000',
      country: 'Vietnam',
    },
    orderItems: [
      {
        id: 'oi-005a',
        productVariantId: 'v004c',
        productName: 'Nike Air Max 270 React',
        variantName: 'Black / Size 40',
        quantity: 1,
        unitPrice: 129,
        subtotal: 129,
      },
      {
        id: 'oi-005b',
        productVariantId: 'v005a',
        productName: "Levi's 511 Slim Fit Jeans",
        variantName: 'Dark Blue / W30 L32',
        quantity: 1,
        unitPrice: 69,
        subtotal: 69,
      },
      {
        id: 'oi-005c',
        productVariantId: 'v010a',
        productName: 'La Mer Crème de la Mer',
        variantName: '15ml',
        quantity: 1,
        unitPrice: 95,
        subtotal: 95,
      },
    ],
    createdAt: '2024-02-15T13:30:00Z',
  },

  // ─── CANCELLED ───────────────────────────────────────────
  {
    id: 'ord-006',
    userId: 'mock-user-id',
    status: 'CANCELLED',
    totalAmount: 1799,
    shippingAddress: {
      firstName: 'Nguyễn',
      lastName: 'Văn A',
      email: 'user@shopnow.com',
      phone: '0901234567',
      street: '123 Nguyễn Huệ',
      city: 'Hồ Chí Minh',
      state: 'HCM',
      zipCode: '700000',
      country: 'Vietnam',
    },
    orderItems: [
      {
        id: 'oi-006a',
        productVariantId: 'v003b',
        productName: 'Samsung 4K OLED Smart TV 55"',
        variantName: '65 inch',
        quantity: 1,
        unitPrice: 1799,
        subtotal: 1799,
      },
    ],
    createdAt: '2024-01-20T16:00:00Z',
  },
];
